import { beforeEach, describe, expect, it, vi } from 'vitest';
import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { I18nextProvider } from 'react-i18next';
import i18n from 'i18next';
import type { ComponentProps } from 'react';
import type { GitRepositoryCompareSummary } from '@repo/types';
import { TooltipProvider } from '@/components/ui/tooltip';
import { GitRepositoryStatusBar } from './GitRepositoryStatusBar';

const mockGitRepositoryService = vi.hoisted(() => ({
  getBranch: vi.fn(),
  listPullRequests: vi.fn(),
  createPullRequest: vi.fn(),
}));

const mockSessionService = vi.hoisted(() => ({
  getGitDiff: vi.fn(),
}));

const COMPARE_URL = 'https://github.com/acme/widgets/compare/main...ccbricks/test';

vi.mock('@/services/git-repository.service', () => ({
  gitRepositoryService: mockGitRepositoryService,
}));

vi.mock('@/services/session.service', () => ({
  sessionService: mockSessionService,
}));

beforeEach(async () => {
  vi.clearAllMocks();
  mockSessionService.getGitDiff.mockResolvedValue(null);
  Object.defineProperty(window, 'open', {
    value: vi.fn(),
    writable: true,
  });
  Object.defineProperty(navigator, 'clipboard', {
    value: { writeText: vi.fn().mockResolvedValue(undefined) },
    configurable: true,
  });

  await i18n.init({
    lng: 'en',
    resources: {
      en: {
        translation: {
          gitStatus: {
            openRepository: 'Open repository on GitHub',
            openBranch: 'Open branch on GitHub',
            copyBranch: 'Copy branch name',
            branchCopied: 'Branch name copied',
            branchCopyError: 'Failed to copy branch name',
            openPullRequest: 'Open pull request',
            createPullRequest: 'Create PR',
            createDraftPullRequest: 'Create draft PR',
            createPullRequestManually: 'Create PR manually',
            createPullRequestOptions: 'Pull request options',
            createPullRequestDisabledNoDiff: 'No changes to create a pull request',
            createPullRequestError: 'Failed to create pull request',
            metadataDialog: {
              title: 'Generate PR metadata',
              description:
                'The pull request title and description are generated by AI. Local git diff, commits, changed file names, and pull request templates are sent to the foundation model, but they are not stored or used for retraining.',
              cancel: 'Cancel',
            },
            status: {
              open: 'Open',
              draft: 'Draft',
              closed: 'Closed',
              merged: 'Merged',
              none: 'No pull request',
            },
          },
        },
      },
    },
  });
});

function renderStatusBar(props: Partial<ComponentProps<typeof GitRepositoryStatusBar>> = {}) {
  return render(
    <I18nextProvider i18n={i18n}>
      <TooltipProvider delayDuration={0}>
        <GitRepositoryStatusBar
          sessionId="019729a8-0000-7000-8000-000000000000"
          owner="acme"
          repo="widgets"
          headBranch="ccbricks/test"
          baseBranch="main"
          sessionTitle="Update widgets"
          {...props}
        />
      </TooltipProvider>
    </I18nextProvider>
  );
}

function deferred<T>() {
  let resolve!: (value: T) => void;
  const promise = new Promise<T>(innerResolve => {
    resolve = innerResolve;
  });
  return { promise, resolve };
}

function gitDiff(
  overrides: Partial<GitRepositoryCompareSummary> = {}
): GitRepositoryCompareSummary {
  return {
    html_url: COMPARE_URL,
    ahead_by: 1,
    behind_by: 0,
    total_commits: 1,
    additions: 2,
    deletions: 0,
    ...overrides,
  };
}

describe('GitRepositoryStatusBar', () => {
  it('shows existing pull request details and opens the pull request number directly', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: { html_url: COMPARE_URL },
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({
      pulls: [
        {
          number: 4,
          title: 'Update widgets',
          state: 'closed',
          draft: false,
          merged: true,
          html_url: 'https://github.com/acme/widgets/pull/4',
          head: { ref: 'ccbricks/test', label: 'acme:ccbricks/test' },
          base: { ref: 'main', label: 'acme:main' },
        },
      ],
    });

    renderStatusBar();

    const pullButton = await screen.findByRole('button', { name: '#4' });
    expect(screen.getByText('widgets')).toBeTruthy();
    expect(screen.getByText('ccbricks/test')).toBeTruthy();
    expect(screen.queryByText('Merged')).toBeNull();
    const pullIcon = document.body.querySelector('.lucide-git-merge');
    expect(pullIcon).toBeTruthy();
    expect(pullButton.querySelector('svg')).toBeNull();

    fireEvent.click(pullIcon!);
    expect(window.open).not.toHaveBeenCalled();
    fireEvent.click(pullButton);
    expect(window.open).toHaveBeenCalledWith(
      'https://github.com/acme/widgets/pull/4',
      '_blank',
      'noopener,noreferrer'
    );
  });

  it('keeps branch copy and open actions in the branch menu', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });

    renderStatusBar();

    const branchButton = await screen.findByRole('button', { name: 'ccbricks/test' });
    fireEvent.pointerDown(branchButton, { button: 0, ctrlKey: false });
    fireEvent.click(await screen.findByText('Copy branch name'));
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith('ccbricks/test');

    fireEvent.pointerDown(branchButton, { button: 0, ctrlKey: false });
    fireEvent.click(await screen.findByText('Open branch on GitHub'));
    expect(window.open).toHaveBeenCalledWith(
      'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      '_blank',
      'noopener,noreferrer'
    );
  });

  it('hides the open branch action until the remote branch exists', async () => {
    mockGitRepositoryService.getBranch.mockRejectedValue(new Error('Branch not found'));
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });

    renderStatusBar();

    await waitFor(() => expect(mockGitRepositoryService.getBranch).toHaveBeenCalled());
    const branchButton = await screen.findByRole('button', { name: 'ccbricks/test' });
    fireEvent.pointerDown(branchButton, { button: 0, ctrlKey: false });

    expect(await screen.findByText('Copy branch name')).toBeTruthy();
    expect(screen.queryByText('Open branch on GitHub')).toBeNull();
  });

  it('uses a commit icon when no pull request exists', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });
    mockSessionService.getGitDiff.mockResolvedValue(gitDiff());

    renderStatusBar();

    expect(await screen.findByRole('button', { name: 'Create PR' })).toHaveProperty(
      'disabled',
      false
    );
    expect(document.body.querySelector('.lucide-git-commit-vertical')).toBeTruthy();
    expect(screen.queryByText('#')).toBeNull();
  });

  it('shows a disabled pull request create button when there is no diff', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: gitDiff({ ahead_by: 0, total_commits: 0, additions: 0 }),
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });
    mockSessionService.getGitDiff.mockResolvedValue(
      gitDiff({ ahead_by: 0, total_commits: 0, additions: 0 })
    );

    renderStatusBar();

    const button = await screen.findByRole('button', { name: 'Create PR' });
    expect(button).toHaveProperty('disabled', true);
    expect(screen.getByRole('button', { name: 'Pull request options' })).toHaveProperty(
      'disabled',
      true
    );
    const buttonGroup = button.closest('span');
    expect(buttonGroup).toBeTruthy();
    fireEvent.pointerMove(buttonGroup!);
    fireEvent.pointerOver(buttonGroup!);
    fireEvent.mouseMove(buttonGroup!);

    expect(
      (await screen.findAllByText('No changes to create a pull request')).length
    ).toBeGreaterThan(0);
  });

  it('keeps pull request creation enabled when the local diff is unavailable', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });
    mockSessionService.getGitDiff.mockRejectedValue(new Error('Git diff unavailable'));

    renderStatusBar();

    expect(await screen.findByRole('button', { name: 'Create PR' })).toHaveProperty(
      'disabled',
      false
    );
  });

  it('refreshes the local diff when the refresh key changes', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });
    mockSessionService.getGitDiff
      .mockResolvedValueOnce(gitDiff())
      .mockResolvedValueOnce(gitDiff({ additions: 5, deletions: 1 }));

    const { rerender } = renderStatusBar({ diffRefreshKey: 0 });
    expect(await screen.findByText('+2')).toBeTruthy();

    rerender(
      <I18nextProvider i18n={i18n}>
        <TooltipProvider delayDuration={0}>
          <GitRepositoryStatusBar
            sessionId="019729a8-0000-7000-8000-000000000000"
            owner="acme"
            repo="widgets"
            headBranch="ccbricks/test"
            baseBranch="main"
            sessionTitle="Update widgets"
            diffRefreshKey={1}
          />
        </TooltipProvider>
      </I18nextProvider>
    );

    expect(await screen.findByText('+5')).toBeTruthy();
    expect(screen.getByText('-1')).toBeTruthy();
    expect(mockSessionService.getGitDiff).toHaveBeenCalledTimes(2);
    expect(mockGitRepositoryService.getBranch).toHaveBeenCalledTimes(1);
  });

  it('uses a red closed icon for closed pull requests', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({
      pulls: [
        {
          number: 8,
          title: 'Closed widgets',
          state: 'closed',
          draft: false,
          merged: false,
          html_url: 'https://github.com/acme/widgets/pull/8',
          head: { ref: 'ccbricks/test', label: 'acme:ccbricks/test' },
          base: { ref: 'main', label: 'acme:main' },
        },
      ],
    });

    renderStatusBar();

    expect(await screen.findByText('#8')).toBeTruthy();
    const closedIcon = document.body.querySelector('.lucide-git-pull-request-closed');
    expect(closedIcon).toBeTruthy();
    expect(closedIcon?.getAttribute('class')).toContain('text-red-600');
    expect(screen.queryByText('Closed')).toBeNull();
  });

  it('shows pull request status when hovering the status icon', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({
      pulls: [
        {
          number: 8,
          title: 'Closed widgets',
          state: 'closed',
          draft: false,
          merged: false,
          html_url: 'https://github.com/acme/widgets/pull/8',
          head: { ref: 'ccbricks/test', label: 'acme:ccbricks/test' },
          base: { ref: 'main', label: 'acme:main' },
        },
      ],
    });

    renderStatusBar();

    await screen.findByText('#8');
    const iconWrapper = document.body.querySelector(
      '.lucide-git-pull-request-closed'
    )?.parentElement;
    expect(iconWrapper).toBeTruthy();
    fireEvent.pointerMove(iconWrapper!);
    fireEvent.pointerOver(iconWrapper!);
    fireEvent.mouseMove(iconWrapper!);

    expect((await screen.findAllByText('Closed')).length).toBeGreaterThan(0);
  });

  it('requires confirmation before creating a pull request with generated metadata', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });
    mockSessionService.getGitDiff.mockResolvedValue(gitDiff());
    mockGitRepositoryService.createPullRequest.mockResolvedValue({
      number: 6,
      title: 'Update widgets',
      state: 'open',
      draft: false,
      merged: false,
      html_url: 'https://github.com/acme/widgets/pull/6',
      head: { ref: 'ccbricks/test', label: 'acme:ccbricks/test' },
      base: { ref: 'main', label: 'acme:main' },
    });

    renderStatusBar();

    fireEvent.click(await screen.findByRole('button', { name: 'Create PR' }));
    let dialog = await screen.findByRole('dialog');
    expect(within(dialog).getByText('Generate PR metadata')).toBeTruthy();
    expect(within(dialog).getByText(/not stored or used for retraining/)).toBeTruthy();
    expect(mockGitRepositoryService.createPullRequest).not.toHaveBeenCalled();

    fireEvent.click(within(dialog).getByRole('button', { name: 'Cancel' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
    expect(mockGitRepositoryService.createPullRequest).not.toHaveBeenCalled();

    fireEvent.click(screen.getByRole('button', { name: 'Create PR' }));
    dialog = await screen.findByRole('dialog');
    fireEvent.click(within(dialog).getByRole('button', { name: 'Create PR' }));

    await waitFor(() => {
      expect(mockGitRepositoryService.createPullRequest).toHaveBeenCalledWith('acme/widgets', {
        title: 'Update widgets',
        head: 'acme:ccbricks/test',
        base: 'main',
        draft: false,
        session_id: '019729a8-0000-7000-8000-000000000000',
        language: 'en',
      });
    });
  });

  it('creates a draft pull request from the split button menu', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockSessionService.getGitDiff.mockResolvedValue({
      html_url: COMPARE_URL,
      ahead_by: 2,
      behind_by: 0,
      total_commits: 2,
      additions: 60,
      deletions: 6,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });
    mockGitRepositoryService.createPullRequest.mockResolvedValue({
      number: 5,
      title: 'Update widgets',
      state: 'open',
      draft: true,
      merged: false,
      html_url: 'https://github.com/acme/widgets/pull/5',
      head: { ref: 'ccbricks/test', label: 'acme:ccbricks/test' },
      base: { ref: 'main', label: 'acme:main' },
    });

    renderStatusBar();

    await screen.findByText('+60');
    expect(mockSessionService.getGitDiff).toHaveBeenCalledWith(
      '019729a8-0000-7000-8000-000000000000'
    );
    expect(screen.getByRole('button', { name: 'Create PR' }).querySelector('svg')).toBeNull();
    expect(document.body.querySelector('.lucide-git-pull-request')).toBeNull();
    fireEvent.pointerDown(screen.getByRole('button', { name: 'Pull request options' }), {
      button: 0,
      ctrlKey: false,
    });
    await screen.findByText('Create draft PR');
    expect(screen.getByText('Create PR manually')).toBeTruthy();
    expect(document.body.querySelector('.lucide-git-pull-request-arrow')).toBeTruthy();
    expect(document.body.querySelector('.lucide-git-pull-request-draft')).toBeTruthy();
    fireEvent.click(screen.getByText('Create draft PR'));
    const dialog = await screen.findByRole('dialog');
    expect(within(dialog).getByText('Generate PR metadata')).toBeTruthy();
    expect(mockGitRepositoryService.createPullRequest).not.toHaveBeenCalled();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Create draft PR' }));

    await waitFor(() => {
      expect(mockGitRepositoryService.createPullRequest).toHaveBeenCalledWith('acme/widgets', {
        title: 'Update widgets',
        head: 'acme:ccbricks/test',
        base: 'main',
        draft: true,
        session_id: '019729a8-0000-7000-8000-000000000000',
        language: 'en',
      });
    });
    expect(screen.getByText('+60')).toBeTruthy();
    expect(screen.getByText('-6')).toBeTruthy();
    expect(window.open).toHaveBeenCalledWith(
      'https://github.com/acme/widgets/pull/5',
      '_blank',
      'noopener,noreferrer'
    );
  });

  it('opens GitHub manual pull request creation from the split button menu', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });
    mockSessionService.getGitDiff.mockResolvedValue(gitDiff());

    renderStatusBar();

    await screen.findByRole('button', { name: 'Create PR' });
    fireEvent.pointerDown(screen.getByRole('button', { name: 'Pull request options' }), {
      button: 0,
      ctrlKey: false,
    });
    fireEvent.click(await screen.findByText('Create PR manually'));

    expect(mockGitRepositoryService.createPullRequest).not.toHaveBeenCalled();
    expect(window.open).toHaveBeenCalledWith(
      'https://github.com/acme/widgets/compare/main...ccbricks%2Ftest?expand=1',
      '_blank',
      'noopener,noreferrer'
    );
  });

  it('still shows pull request details without an error label when branch details fail', async () => {
    mockGitRepositoryService.getBranch.mockRejectedValue(new Error('Branch not found'));
    mockGitRepositoryService.listPullRequests.mockResolvedValue({
      pulls: [
        {
          number: 4,
          title: 'Update widgets',
          state: 'open',
          draft: false,
          merged: false,
          html_url: 'https://github.com/acme/widgets/pull/4',
          head: { ref: 'ccbricks/test', label: 'acme:ccbricks/test' },
          base: { ref: 'main', label: 'acme:main' },
        },
      ],
    });

    renderStatusBar();

    expect(await screen.findByText('#4')).toBeTruthy();
    expect(
      document.body.querySelector('.lucide-git-pull-request-arrow')?.getAttribute('class')
    ).toContain('text-green-600');
    expect(screen.queryByText('Open')).toBeNull();
    expect(screen.queryByText('GitHub details unavailable')).toBeNull();
  });

  it('does not show the pull request create button until the remote branch exists', async () => {
    mockGitRepositoryService.getBranch.mockRejectedValue(new Error('Branch not found'));
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });

    renderStatusBar();

    await waitFor(() => {
      expect(mockGitRepositoryService.getBranch).toHaveBeenCalledWith(
        'acme/widgets',
        'ccbricks/test',
        'main'
      );
    });
    expect(screen.queryByRole('button', { name: 'Create PR' })).toBeNull();
  });

  it('keeps existing pull request details when a remote refresh fails', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: null,
    });
    mockSessionService.getGitDiff.mockResolvedValue(gitDiff());
    mockGitRepositoryService.listPullRequests
      .mockResolvedValueOnce({
        pulls: [
          {
            number: 4,
            title: 'Update widgets',
            state: 'open',
            draft: false,
            merged: false,
            html_url: 'https://github.com/acme/widgets/pull/4',
            head: { ref: 'ccbricks/test', label: 'acme:ccbricks/test' },
            base: { ref: 'main', label: 'acme:main' },
          },
        ],
      })
      .mockRejectedValueOnce(new Error('Pulls unavailable'));

    const { rerender } = renderStatusBar({ remoteRefreshKey: 0 });

    expect(await screen.findByText('#4')).toBeTruthy();

    rerender(
      <I18nextProvider i18n={i18n}>
        <TooltipProvider delayDuration={0}>
          <GitRepositoryStatusBar
            sessionId="019729a8-0000-7000-8000-000000000000"
            owner="acme"
            repo="widgets"
            headBranch="ccbricks/test"
            baseBranch="main"
            sessionTitle="Update widgets"
            remoteRefreshKey={1}
          />
        </TooltipProvider>
      </I18nextProvider>
    );

    await waitFor(() => expect(mockGitRepositoryService.listPullRequests).toHaveBeenCalledTimes(2));
    expect(screen.getByText('#4')).toBeTruthy();
    expect(screen.queryByRole('button', { name: 'Create PR' })).toBeNull();
  });

  it('refreshes remote branch details when the remote refresh key changes', async () => {
    mockGitRepositoryService.getBranch
      .mockRejectedValueOnce(new Error('Branch not found'))
      .mockResolvedValueOnce({
        name: 'ccbricks/test',
        html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
        compare: null,
      });
    mockGitRepositoryService.listPullRequests.mockResolvedValue({ pulls: [] });
    mockSessionService.getGitDiff.mockResolvedValue(gitDiff());

    const { rerender } = renderStatusBar({ diffRefreshKey: 0, remoteRefreshKey: 0 });

    await waitFor(() => expect(mockGitRepositoryService.getBranch).toHaveBeenCalledTimes(1));
    expect(screen.queryByRole('button', { name: 'Create PR' })).toBeNull();

    rerender(
      <I18nextProvider i18n={i18n}>
        <TooltipProvider delayDuration={0}>
          <GitRepositoryStatusBar
            sessionId="019729a8-0000-7000-8000-000000000000"
            owner="acme"
            repo="widgets"
            headBranch="ccbricks/test"
            baseBranch="main"
            sessionTitle="Update widgets"
            remoteRefreshKey={1}
          />
        </TooltipProvider>
      </I18nextProvider>
    );

    const button = await screen.findByRole('button', { name: 'Create PR' });
    await waitFor(() => expect(button).toHaveProperty('disabled', false));
    expect(mockGitRepositoryService.getBranch).toHaveBeenCalledTimes(2);
    expect(mockGitRepositoryService.listPullRequests).toHaveBeenCalledTimes(2);
    expect(mockSessionService.getGitDiff).toHaveBeenCalledTimes(1);
  });

  it('treats pull request list failures as no existing pull request', async () => {
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/test',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Ftest',
      compare: {
        html_url: COMPARE_URL,
        additions: 9,
        deletions: 1,
      },
    });
    mockGitRepositoryService.listPullRequests.mockRejectedValue(new Error('Pulls unavailable'));

    renderStatusBar();

    expect(await screen.findByText('+9')).toBeTruthy();
    expect(screen.getByRole('button', { name: 'Create PR' })).toBeTruthy();
    expect(screen.queryByText('GitHub details unavailable')).toBeNull();
  });

  it('clears stale pull request data when switching sessions and ignores old responses', async () => {
    const oldPulls = deferred<{
      pulls: Array<{
        number: number;
        title: string;
        state: 'open';
        draft: boolean;
        merged: boolean;
        html_url: string;
        head: { ref: string; label: string };
        base: { ref: string; label: string };
      }>;
    }>();
    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/old',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Fold',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockReturnValueOnce(oldPulls.promise);

    const { rerender } = renderStatusBar({
      sessionId: '019729a8-0000-7000-8000-000000000001',
      headBranch: 'ccbricks/old',
    });

    expect(await screen.findByText('ccbricks/old')).toBeTruthy();

    mockGitRepositoryService.getBranch.mockResolvedValue({
      name: 'ccbricks/new',
      html_url: 'https://github.com/acme/widgets/tree/ccbricks%2Fnew',
      compare: null,
    });
    mockGitRepositoryService.listPullRequests.mockResolvedValueOnce({ pulls: [] });

    rerender(
      <I18nextProvider i18n={i18n}>
        <TooltipProvider delayDuration={0}>
          <GitRepositoryStatusBar
            sessionId="019729a8-0000-7000-8000-000000000002"
            owner="acme"
            repo="widgets"
            headBranch="ccbricks/new"
            baseBranch="main"
            sessionTitle="Update widgets"
          />
        </TooltipProvider>
      </I18nextProvider>
    );

    expect(await screen.findByText('ccbricks/new')).toBeTruthy();
    await act(async () => {
      oldPulls.resolve({
        pulls: [
          {
            number: 7,
            title: 'Old PR',
            state: 'open',
            draft: false,
            merged: false,
            html_url: 'https://github.com/acme/widgets/pull/7',
            head: { ref: 'ccbricks/old', label: 'acme:ccbricks/old' },
            base: { ref: 'main', label: 'acme:main' },
          },
        ],
      });
      await Promise.resolve();
    });

    expect(screen.queryByText('#7')).toBeNull();
  });
});
